### ISSUE TITLE
Update all published README.md files.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1157]
Now that TS is in common code, all sims require a compilation step before they can be run.  This is not currently reflected in README.md files for published sims.

When updating README.md files, be sure to take https://github.com/phetsims/chipper/issues/1136 into consideration. Prototypes have a version >= 1.X.X, but should not have a published README.md.

**Comment by samreid** [comment]
I updated the template but thought it would be wise to request review before applying it to 100+ repos:

<details>

```diff

Index: templates/README-published.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/templates/README-published.md b/templates/README-published.md
--- a/templates/README-published.md	(revision a777699ffdf0554147a19b45390415eac0d3ff38)
+++ b/templates/README-published.md	(date 1638806796446)
@@ -23,9 +23,22 @@
 ```
 {{CLONE_COMMANDS}}
 ```
-(2) Start an http-server
+
+(2) Change directory to `chipper/`, and install dependencies by running `npm install`
+
+(3) Still in directory `chipper/`, transpile the code to JavaScript by running `node js/scripts/transpile.js` (or add `--watch` to enable a file watching process)
+
+(4) Start an http-server
 
-(3) Open `http://localhost/{{REPOSITORY}}/{{REPOSITORY}}_en.html` (You will probably need to modify this URL based on your HTTP port and relative path.)
+(5) Open in the browser: `http://localhost/{{REPOSITORY}}/{{REPOSITORY}}_en.html` (You will probably need to modify this URL based on your HTTP port and relative path.)
+
+#### Optional: Build the simulation into a single file
+
+(1) Change directory to the simulation directory: `cd {{REPOSITORY}}`
+
+(2) Build the sim: `grunt --brands=adapted-from-phet`
+
+(3) Open in the browser: `http://localhost/{{REPOSITORY}}/build/adapted-from-phet/{{REPOSITORY}}_en_adapted-from-phet.html` (You will probably need to modify this URL based on your HTTP port and relative path.)
 
 ### Get Involved
 

```

</details>

@pixelzoom @zepumph or @jonathanolson can you please review?

**Comment by pixelzoom** [comment]
The proposed changes in https://github.com/phetsims/chipper/issues/1157#issuecomment-986920909 look OK to me.

**Comment by samreid** [comment]
Thanks, I committed the change to the template, then changes to 92 published READMEs.  3 were prototypes so I skipped them, I think it was geometric optics, greenhouse and normal modes.  Can this issue be closed?

**Comment by pixelzoom** [comment]
I tested the deployed README.md for gas-properties.  It's broken, missing:

```
git clone https://github.com/phetsims/perennial.git perennial
```

So this steps fails:

```
% cd chipper
% node js/scripts/transpile.js
couldnt parse status cache, making a clean one
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, open '../perennial/data/active-repos'
    at Object.open
...
```

This problem appears to be present in all of the README.md files that I checked.

Back to @samreid.

**Comment by pixelzoom** [comment]
There's an `npm install` missing between these 2 steps:

```
(1) Change directory to the simulation directory: cd gas-properties

(2) Build the sim: grunt --brands=adapted-from-phet
``

**Comment by pixelzoom** [comment]
Looks like there's at least one other `git clone` missing.

```
% cd gas-properties 
% npm install
% grunt --brands=adapted-from-phet
Running "lint-all" task

Running "report-media" task
skipping repo (not checked out): phet-io
skipping repo (not checked out): phet-io-client-guides
skipping repo (not checked out): phet-io-wrappers
skipping repo (not checked out): studio

Running "clean" task

Running "build" task
Fatal error: Perennial task failed:
Error: Cannot find module 'winston'
Require stack:
- /Users/cmalley/Downloads/junk/perennial-alias/js/common/execute.js
- /Users/cmalley/Downloads/junk/chipper/js/grunt/copySupplementalPhetioFiles.js
- /Users/cmalley/Downloads/junk/chipper/js/grunt/buildRunnable.js
- /Users/cmalley/Downloads/junk/chipper/js/grunt/Gruntfile.js
- /Users/cmalley/Downloads/junk/gas-properties/Gruntfile.js
- /Users/cmalley/Downloads/junk/gas-properties/node_modules/grunt/lib/grunt/task.js
- /Users/cmalley/Downloads/junk/gas-properties/node_modules/grunt/lib/grunt.js
- /usr/local/lib/node_modules/grunt-cli/bin/grunt
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/cmalley/Downloads/junk/perennial-alias/js/common/execute.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
Full Error details:
Error: Cannot find module 'winston'
Require stack:
- /Users/cmalley/Downloads/junk/perennial-alias/js/common/execute.js
- /Users/cmalley/Downloads/junk/chipper/js/grunt/copySupplementalPhetioFiles.js
- /Users/cmalley/Downloads/junk/chipper/js/grunt/buildRunnable.js
- /Users/cmalley/Downloads/junk/chipper/js/grunt/Gruntfile.js
- /Users/cmalley/Downloads/junk/gas-properties/Gruntfile.js
- /Users/cmalley/Downloads/junk/gas-properties/node_modules/grunt/lib/grunt/task.js
- /Users/cmalley/Downloads/junk/gas-properties/node_modules/grunt/lib/grunt.js
- /usr/local/lib/node_modules/grunt-cli/bin/grunt
```

**Comment by samreid** [comment]
I regenerated the README files, skipping the prototypes and adding `grunt published-README` for example-sim.  I tested in acid-base-solutions that the transpile and grunt steps worked properly.

**Comment by pixelzoom** [comment]
> git clone https://github.com/phetsims/perennial.git perennial-alias

This line is repeated twice in every README.md that I inspected. 


> (3) Change directory to chipper cd ../chipper/, then transpile the code to JavaScript by running 1node js/scripts/transpile.js --watch`

Did you really want to include `--watch` here? That will block further input to the Terminal/Command window, and may be confusing to users who just want to run the sim.

**Comment by samreid** [comment]
I pushed a fix that omits the duplicate perennial-alias, but will wait on pushing all READMEs until we finish discussing about `--watch`.  I included `--watch` intentionally because I think we should recommend that as the way to get clients up and running.  It also matches what clients will see when running `http-server` -- that it starts a continuing process, and they need another terminal to continue.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/chipper/commit/a8f4629b91830994b572a71f0d87554a83d0155a doesn't look like a solution, it looks like an (undesireable) workaround for other problems:
(1) Why doesn't getPhetLibs report problems with duplictes?
(2) Why is perennial-alias not in all phetLibs? It's specified in build.json.
(3) Why is perennial in phetLibs? It's not in build.json, and it should not be specified in package.json.

**Comment by samreid** [comment]
> (1) Why doesn't getPhetLibs report problems with duplicates, or at least filter out duplicates?

The duplicate was being added by buggy code in generateREADME.  `getPhetLibs` ends like so: 

```js
    // sort and remove duplicates
    return _.uniq( phetLibs.sort() );
```

> (2) Why is perennial-alias not in all phetLibs? It's specified in build.json.

It is in phetLibs, that's why my incorrectly adding it in generateREADME it appeared twice.

> (3) Why is perennial in phetLibs? It's not in build.json, and it should not be specified in package.json.

It wasn't in phetLibs, but I thought we needed it for transpile.js, so I added it in generateREADME.

Perhaps the way out of these problems is to make Transpiler.js read from perennial-alias instead of perennial.  Then we can remove the workaround https://github.com/phetsims/chipper/commit/a8f4629b91830994b572a71f0d87554a83d0155a and everything else should work OK.  Sound OK?

**Comment by pixelzoom** [comment]
> Perhaps the way out of these problems is to make Transpiler.js read from perennial-alias instead of perennial.  ...

I'm not familiar with Transpiler.js (and don't have time to dig into it) so I can't advise.

> ... will wait on pushing all READMEs until we finish discussing about `--watch`.

I don't feel strongly about this. Just pointing out that `--watch` will result in a process that doesn't return, so the user will need to open another Terminal/Command window to proceed.

**Comment by samreid** [comment]
> I don't feel strongly about this. Just pointing out that `--watch` will result in a process that doesn't return, so the user will need to open another Terminal/Command window to proceed. 

Agreed, thanks.  I updated the wording in the commit.

**Comment by samreid** [comment]
I published another batch with the proposed changes.  @pixelzoom want to spot check anything?

**Comment by pixelzoom** [comment]
👍🏻

**Comment by pixelzoom** [comment]
Reopening.  There is still a problem with the `npm install` instructons.

README.md says:

```
cd chipper
npm install
cd ../perennial
npm install
cd ../perennial-alias
npm install
cd ../example-sim
npm install
```

PhET Development Overview says:

```
cd chipper
npm install
cd ../perennial-alias
npm install
cd ../${directory of the sim you are working on}
npm install
```

In Slack, @samreid said:
> I don’t think perennial install is required.

If that's indeed the case, then README.md needs to be revised again.

**Comment by samreid** [comment]
It feels unfortunate that there is so much copy/paste across all the README.md files.  Would be nice to centralize as much as possible, and each sim can just provide information specific to itself.

**Comment by samreid** [comment]
In discussion with @marlitas, we concluded that the advantages of individual readme files outweighs the disadvantages.  But it does seem best to `npm install` perennial so I added that to the PhET Development Overview.  So when I regenerate the README files it will mostly have changes from https://github.com/phetsims/chipper/issues/1176

**Comment by samreid** [comment]
We also observed that several package.jsons have superfluous eslint rule overrides which are leading to HTML file changes on `grunt update`.  We are correcting those as we identify them, and will make a larger issue to review all overrides.

**Comment by samreid** [comment]
@marlitas and I updated all the readmes as described in the preceding comments.  @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Spot checked a few README.md files.  Looks good. Closing.
