### ISSUE TITLE
window is not defined during build

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#84]
```
npm install
grunt
```

:point_right: 

```
Running "requirejs:build" (requirejs) task
>> Error: ReferenceError: window is not defined
>> In module tree:
>>     balloons-and-static-electricity-main
>>       JOIST/Sim
>>         JOIST/NavigationBar
>>           JOIST/PhetButton
>>             JOIST/PhetMenu
>>               JOIST/AboutDialog
>>                 string
>> 
>>     at Object.load (eval at <anonymous> (/Users/samreid/github/balloons-and-static-electricity/node_modules/requirejs/bin/r.js:25458:38), <anonymous>:66:67)
Warning: Task "requirejs:build" failed. Use --force to continue.
```

Perhaps due to changes in npm install dependencies?

**Comment by samreid** [comment]
> Perhaps due to changes in npm install dependencies?

Nope, I'm seeing this in older projects (with stale node_modules) as well.

**Comment by samreid** [comment]
This bug was introduced in 80de24ce458b735436262beab92a81e9e31485e2 when `queryParameterStrings` popped out of the `if ( !config.isBuild ) {` statement.  `window` is only defined for a browser session.

**Comment by samreid** [comment]
Fixed above, reassigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Ah... So that's what the comments "Browser version first" and "For compiler time" (sic) mean? Methinks that needs to be documented better.  Am I'm still not entered clean what the difference is between the 'then' and 'else' blocks. @samreid can you please take a stab at clarifying?

**Comment by pixelzoom** [comment]
Moved documentation issue to https://github.com/phetsims/chipper/issues/85. Closing.
